### ISSUE TITLE
Issue With runHTS.py

### ISSUE THREAD

**Issue by adwarner** [CollinRooney12/htsprophet#3]
Hi, 

Seems to be a bug when running runHTS.py in python 3. There is an issue with holidays producing ValueError: holidays must be a DataFrame with 'ds' and 'holiday' columns, despite it being clearly defined.

**Comment by mesk421** [comment]
Hi,

There are any news about the "holidays" bug?
Alternatively, can I avoid specifying the holidays DataFrame, since my timeseries have monthly frequency?

**Comment by jordy-van-appeven** [comment]
This issue can be solved by chaning all prophet(..) Positional arguments to keyword arguments as explained here https://stackoverflow.com/questions/48450418/hts-prophet-holidays-issue/51400527#51400527

**Comment by emorfam** [comment]
Open PR
#7
